name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_lib:
    path: ../../packages/shared_lib

  cupertino_icons: ^1.0.6
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  freezed: ^2.5.2
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: